# Generated by Django 4.2.26 on 2025-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('oficio', models.CharField(max_length=100)),
                ('materia', models.TextField()),
                ('fecha_oficio', models.DateField()),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('asignacion', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
