# Generated by Django 4.2.26 on 2025-11-27 19:22

from django.db import migrations, models
import django.db.models.deletion
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=juridica.models.archivo_upload_to)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='juridica.registrojuridico')),
            ],
        ),
    ]
