# Generated by Django 4.2.26 on 2025-12-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrojuridico',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
