# Generated by Django 4.2.26 on 2025-12-22 15:29

from django.db import migrations, models
import django.db.models.deletion
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0003_registrojuridico_terminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha_termino', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_juridica', to='juridica.registrojuridico')),
            ],
        ),
    ]
