# Generated by Django 4.2.26 on 2025-12-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0004_respuestajuridica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrojuridico',
            name='asignacion',
        ),
        migrations.AddField(
            model_name='registrojuridico',
            name='asignaciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
