# Generated by Django 3.2.15 on 2025-12-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0005_remove_registrojuridico_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrojuridico',
            name='cc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registrojuridico',
            name='dirigido_a',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
