# Generated by Django 3.2.15 on 2026-02-02 14:33

from django.db import migrations, models
import django.db.models.deletion
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0006_auto_20251223_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSumario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_creacion', models.DateField()),
                ('n_da', models.TextField()),
                ('fecha_da', models.DateField()),
                ('fiscal_acargo', models.CharField(max_length=100)),
                ('grado_fiscal', models.CharField(max_length=50)),
                ('materia', models.TextField()),
                ('nombre_apellido_grado_imputado', models.JSONField(blank=True, default=list)),
                ('oficio_fiscalia', models.CharField(max_length=100)),
                ('fecha_fiscalia', models.DateField()),
                ('adjunto_fiscalia', models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario)),
                ('oficio_juridico', models.CharField(max_length=100)),
                ('fecha_juridico', models.DateField()),
                ('adjunto_juridico', models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario)),
                ('sancion', models.JSONField(blank=True, default=list)),
                ('fecha_contrata', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSumario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=juridica.models.archivo_upload_to_sumario)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('sumario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_sumario', to='juridica.registrosumario')),
            ],
        ),
    ]
