# Generated by Django 3.2.15 on 2026-02-11 12:29

from django.db import migrations, models
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0007_documentosumario_registrosumario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosumario',
            name='adjunto_sancion',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='sancion',
            field=models.CharField(max_length=100),
        ),
    ]
