# Generated by Django 3.2.15 on 2026-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0008_auto_20260211_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosumario',
            name='sancion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
