# Generated by Django 3.2.15 on 2026-02-13 12:38

from django.db import migrations, models
import django.db.models.deletion
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0009_alter_registrosumario_sancion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReiterarJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correos', models.CharField(blank=True, max_length=255)),
                ('copias_correos', models.CharField(blank=True, max_length=255)),
                ('fecha_termino', models.DateField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reiteraciones', to='juridica.registrojuridico')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo_reitero_Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to)),
                ('reitero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_reitero', to='juridica.reiterarjuridica')),
            ],
        ),
    ]
