# Generated by Django 3.2.15 on 2026-02-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0010_archivo_reitero_adjunto_reiterarjuridica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reiterarjuridica',
            name='fecha_termino',
        ),
    ]
