# Generated by Django 3.2.15 on 2026-02-13 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0011_remove_reiterarjuridica_fecha_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='reiterarjuridica',
            name='fecha_de_envio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
