# Generated by Django 3.2.15 on 2026-02-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0012_reiterarjuridica_fecha_de_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosumario',
            name='etapa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='n_da',
            field=models.TextField(blank=True, null=True),
        ),
    ]
