# Generated by Django 3.2.15 on 2026-02-24 20:21

from django.db import migrations, models
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0013_auto_20260224_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosumario',
            name='fecha_notificacion_fiscal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='oficio_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='oficio_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='etapa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='fecha_da',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='fecha_fiscalia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='fecha_juridico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='fiscal_acargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='grado_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='materia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='oficio_fiscalia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='oficio_juridico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrosumario',
            name='sancion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
