# Generated by Django 3.2.15 on 2026-03-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0017_registrojuridico_funcionario_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReiterarSumario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correos', models.CharField(blank=True, max_length=255)),
                ('copias_correos', models.CharField(blank=True, max_length=255)),
                ('fecha_de_envio', models.DateField(auto_now_add=True)),
                ('sumario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reiteraciones_sumario', to='juridica.registrosumario')),
            ],
        ),
    ]
