# Generated by Django 3.2.15 on 2026-03-09 20:38

from django.db import migrations, models
import django.db.models.deletion
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0018_reiterarsumario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo_reitero_sumario_Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to)),
                ('sumario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_sumario_reitero', to='juridica.reiterarsumario')),
            ],
        ),
    ]
