# Generated by Django 3.2.15 on 2026-03-12 13:45

from django.db import migrations, models
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0019_archivo_reitero_sumario_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosumario',
            name='archivo_e_1',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='archivo_e_2',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='archivo_e_3',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='archivo_e_4',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
        migrations.AddField(
            model_name='reiterarsumario',
            name='etapa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
