# Generated by Django 3.2.15 on 2026-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0020_auto_20260312_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosumario',
            name='cc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='dirigido_a',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='respuesta',
            field=models.TextField(blank=True),
        ),
    ]
