# Generated by Django 3.2.15 on 2026-03-12 19:49

from django.db import migrations, models
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0021_auto_20260312_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosumario',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='registrosumario',
            name='dirigido_a',
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='archivo_final',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
    ]
