# Generated by Django 3.2.15 on 2026-03-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0022_auto_20260312_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosumario',
            name='archivo_e_2',
        ),
        migrations.RemoveField(
            model_name='registrosumario',
            name='archivo_e_3',
        ),
    ]
