# Generated by Django 3.2.15 on 2026-03-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0023_auto_20260323_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosumario',
            name='archivo_e_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='archivo_e_3',
            field=models.BooleanField(default=False),
        ),
    ]
