# Generated by Django 3.2.15 on 2026-03-24 14:34

from django.db import migrations, models
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0024_auto_20260323_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrosumario',
            old_name='adjunto_juridico',
            new_name='adjunto_baj',
        ),
        migrations.RenameField(
            model_name='registrosumario',
            old_name='fecha_juridico',
            new_name='fecha_baj',
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='adjunto_not_fiscalia',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
    ]
