# Generated by Django 3.2.15 on 2026-03-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0025_auto_20260324_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrosumario',
            old_name='adjunto_baj',
            new_name='adjunto_daj',
        ),
        migrations.RenameField(
            model_name='registrosumario',
            old_name='fecha_baj',
            new_name='fecha_daj',
        ),
    ]
