# Generated by Django 3.2.15 on 2026-04-08 21:14

from django.db import migrations, models
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0026_auto_20260324_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosumario',
            name='Decreto_alcadicio',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='Expediente',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
    ]
