# Generated by Django 3.2.15 on 2026-04-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0027_auto_20260408_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrosumario',
            old_name='Decreto_alcadicio',
            new_name='decreto_alcadicio',
        ),
        migrations.RenameField(
            model_name='registrosumario',
            old_name='Expediente',
            new_name='expediente',
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='fecha_dec_alcadicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='fecha_expediente',
            field=models.DateField(blank=True, null=True),
        ),
    ]
