# Generated by Django 3.2.15 on 2026-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0028_auto_20260408_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrojuridico',
            name='terminado_funcinario',
            field=models.BooleanField(default=False),
        ),
    ]
