# Generated by Django 3.2.15 on 2026-04-10 20:58

from django.db import migrations, models
import juridica.models


class Migration(migrations.Migration):

    dependencies = [
        ('juridica', '0029_registrojuridico_terminado_funcinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosumario',
            name='fecha_instruccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosumario',
            name='intruye_sumario',
            field=models.FileField(blank=True, null=True, upload_to=juridica.models.archivo_upload_to_sumario),
        ),
    ]
