# Generated by Django 3.2.15 on 2026-04-17 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juridica', '0030_auto_20260410_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrojuridico',
            name='funcionario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_asignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
